[project]
name = "nd608-generative-ai-project-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.3",
    "pandas>=2.3.2",
    "ruff>=0.13.1",
    "ty>=0.0.1a21",
]
